name: Docker Build ghcr
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      
env:
  REGISTRY: ghcr.io
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ghcr.io/metrico/qryn-otel-collector
          tags: |
            latest
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./cmd/otel-collector
          file: ./cmd/otel-collector/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
