name: test-pipeline

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        type: manual

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install tools
        run: make install-ci

      - name: Run unit tests and lint
        run: make test-and-lint
